# Generated by Django 4.2 on 2025-10-07 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_diseaseprediction_farm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('predicted_price_per_ton', models.FloatField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('market_trend', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=20)),
                ('forecast_period_days', models.IntegerField(default=30)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
            ],
        ),
    ]