# Generated by Django 4.2 on 2025-10-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_marketprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=20)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('soil_ph', models.FloatField()),
                ('soil_type', models.CharField(choices=[('Sandy', 'Sandy'), ('Clay', 'Clay'), ('Loam', 'Loam'), ('Silt', 'Silt'), ('Peat', 'Peat'), ('Chalky', 'Chalky')], max_length=50)),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('weather_condition', models.CharField(choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Humid', 'Humid'), ('Stormy', 'Stormy')], max_length=20)),
                ('irrigation_method', models.CharField(choices=[('Drip', 'Drip'), ('Sprinkler', 'Sprinkler'), ('Furrow', 'Furrow'), ('Flood', 'Flood'), ('None', 'None')], max_length=20)),
                ('previous_crop', models.CharField(max_length=100)),
                ('days_since_planting', models.IntegerField()),
                ('plant_density', models.IntegerField()),
                ('predicted_pest', models.CharField(max_length=100)),
                ('pest_presence', models.BooleanField()),
                ('severity', models.IntegerField()),
                ('confidence_score', models.FloatField()),
                ('recommended_treatment', models.TextField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
            ],
        ),
    ]