# Generated by Django 5.2.6 on 2025-10-08 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_pestprediction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="croprecommendation",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="diseaseprediction",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="fertilizerrecommendation",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="marketprediction",
            name="prediction_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pestprediction",
            name="prediction_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="yieldprediction",
            name="prediction_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
