# Generated by Django 5.2.6 on 2025-10-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_diseaseprediction_farm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yieldprediction",
            name="satellite_image",
        ),
    ]
