# Generated by Django 5.2.6 on 2025-10-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_yieldprediction_satellite_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diseaseprediction",
            name="farm",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="farm",
        ),
        migrations.RemoveField(
            model_name="satelliteimage",
            name="farm",
        ),
        migrations.RemoveField(
            model_name="farmcrop",
            name="farm",
        ),
        migrations.RemoveField(
            model_name="croprecommendation",
            name="farm",
        ),
        migrations.RemoveField(
            model_name="farmcrop",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="yieldprediction",
            name="farm_crop",
        ),
        migrations.AddField(
            model_name="yieldprediction",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.crop",
            ),
        ),
        migrations.DeleteModel(
            name="WeatherData",
        ),
        migrations.DeleteModel(
            name="Recommendation",
        ),
        migrations.DeleteModel(
            name="SatelliteImage",
        ),
        migrations.DeleteModel(
            name="Farm",
        ),
        migrations.DeleteModel(
            name="FarmCrop",
        ),
    ]
